[package]
name = "scarab"
version = "0.1.0"
authors = ["l1h3r <devin.turner09@gmail.com>"]
edition = "2018"

[dependencies]
wasmlib = { git = "https://github.com/iotaledger/wasp", branch = "develop" }
